site_name: Acelerador state of art
nav:
  - Home: index.md
  - Instalación: install.md
  - Caso de uso: caso_de_uso.md
  - Ontología: ontologia.md
  - Fuentes: fuentes.md
  - Declaración de IA: AI_DECLARATION.md
theme:
  name: material