site_name: Acelerador state of art
nav:
  - Home: index.md
  - Install: install.md
  - Usage: caso_de_uso.md
  - Ontology: ontology.md
  - Fonts: fonts.md
  - Q&A: preguntas.md
  - AI Declaration: AI_declaration.md
theme:
  name: material